name: build_hyperos_test
on:
  workflow_dispatch:
    inputs:
      URL:
        description: "PortROM indirme linki"
        required: true
jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        runs-on:
          - ubuntu-22.04
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@master
      - name: 1. Hazırlık
        run: |
          echo "BASE_ZIP_NAME=miui_UMI_V14.0.4.0.TJBCNXM_23fc5ef4ee_13.0.zip" >> $GITHUB_ENV
          sudo apt install python3 python3-pip aria2 zip p7zip-full tar zipalign zstd openjdk-8-jre
          sudo apt --fix-broken install
          pip3 install --upgrade pip
          pip3 install pycryptodome
          pip3 install setuptools
          pip3 install docopt
          pip3 install requests
          pip3 install beautifulsoup4
          pip3 install --ignore-installed pyyaml
      - name: 2. Port işlemi başlatılıyor.
        run: |
          cd "$GITHUB_WORKSPACE"/
          sudo ./setup.sh
          sudo ./port.sh http://cdnorg.d.miui.com//V14.0.4.0.TJBCNXM/miui_UMI_V14.0.4.0.TJBCNXM_23fc5ef4ee_13.0.zip ${{ github.event.inputs.URL }}
      - name: 3. Workflow siliniyor
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
